splitters:
  RecursiveCharacterTextSplitter:
      chunk_size: 1000
      chunk_overlap: 100
      separators: ["\n\n", "\n", ".", "!", "?", " ", ""]
      keep_separator : True
  TokenTextSplitter:
      chunk_size: 800
      chunk_overlap: 100
      encoding_name: cl100k_base # "cl100k_base", "o200k_base", "p50k_base", "r50k_base" - are cached ...
      # model_name: gpt-3.5-turbo 
      # optionally put model_name instead of encoding_name "gpt-3.5-turbo", "gpt-4", "text-embedding-ada-002", "gpt-3.5-turbo-16k", "gpt-4-1106-preview" ....
  NLTKTextSplitter:
      chunk_size: 800
      chunk_overlap: 100
      language: russian
  SpacyTextSplitter:
      chunk_size: 800
      chunk_overlap: 100
      pipeline: en_core_web_sm # 'sentencizer' ...

file_types:
  .txt:
    loader: TextLoader
    splitter: RecursiveCharacterTextSplitter
  .csv:
    loader: CSVLoader
    splitter: none
  .pdf:
    loader: PDFPlumberLoader
    splitter: NLTKTextSplitter
  .docx:
    loader: UnstructuredWordDocumentLoader
    splitter: NLTKTextSplitter
  .xlsx:
    loader: UnstructuredExcelLoader
    splitter: none
  .html:
    loader: BSHTMLLoader
    splitter: TokenTextSplitter
  .pptx:
    loader: UnstructuredPowerPointLoader
    splitter: NLTKTextSplitter

embedding:
  provider: liteLLM # "yandexGPT", "liteLLM" or "langchain_fake" ("fake" for 000 dummy embeddings)
  dim: 256
  liteLLM:
    model: yandex-embedding
    api_base: http://localhost:4000
    api_key: $$$$$$$$$$$$$$$$$$$
    folder_id: $$$$$$$$$$$$$$$$$$$
  yandexGPT:
    api_key: $$$$$$$$$$$$$$$$$$$
    folder_id: $$$$$$$$$$$$$$$$$$$
    doc_model_name: text-search-doc
    model_version: latest
    sleep_interval: 2.0
    disable_request_logging: false

sources:
  use_local: true
  use_s3: false
  local_path: ./local_docs
  s3:
    s3_bucket: files
    s3_prefix: ""
    endpoint_url: http://localhost:9000
    aws_access_key_id: minioadmin
    aws_secret_access_key: minioadmin
    use_ssl: false
    signature_version: s3v4

storage:
  store_type: pgvector # "milvus" or "pgvector"
  milvus:
    uri: http://localhost:19530  # "https://username:password@in01-12a.aws-us-west-2.vectordb.zillizcloud.com:19538
    collection: doc_vectors
    drop_old: false
    auto_id: true
    alias: default
  pgvector:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: vector_db
    collection: doc_vectors
    use_jsonb: true

search:
  search_query: "the work of a data analyst"
  search_top_k: 5

timeouts:
  perFileSeconds: 90   # hard stop per document

output_dir: ./output_docs
stop_on_error: true

debug: false # additional debug logging and actions
delete_old_vectors: false # delete documents if found a hash match in metadata for a test purpose only
