splitters:
  RecursiveCharacterTextSplitter:
      chunk_size: 1000
      chunk_overlap: 50
      separators: ["\n\n", "\n", " ", ""]
  TokenTextSplitter:
      chunk_size: 500
      chunk_overlap: 50
      encoding_name: cl100k_base
  NLTKTextSplitter:
      chunk_size: 800
      chunk_overlap: 100
      language: russian

file_types:
  .txt:
    loader: TextLoader
    splitter: RecursiveCharacterTextSplitter
  .csv:
    loader: CSVLoader
    splitter: none
  .pdf:
    loader: PDFPlumberLoader
    splitter: TokenTextSplitter
  .docx:
    loader: UnstructuredWordDocumentLoader
    splitter: NLTKTextSplitter
  .xlsx:
    loader: UnstructuredExcelLoader
    splitter: none
  .html:
    loader: UnstructuredHTMLLoader
    splitter: TokenTextSplitter

embedding:
  provider: langchain_fake # "yandexGPT", "liteLLM" or "langchain_fake" ("fake" for 000 dummy embeddings)
  dim: 256
  liteLLM:
    model: yandex-embedding
    api_base: http://172.17.0.1:4000
    api_key: $$$$S
    folder_id: $$$$$
  yandexGPT:
    api_key: $$$$$
    folder_id: $$$$$
    doc_model_name: text-search-doc
    model_version: latest
    sleep_interval: 2.0
    disable_request_logging: false

sources:
  use_local: false
  use_s3: false
  local_path: ./local_docs
  s3:
    s3_bucket: files
    s3_prefix: ""
    endpoint_url: http://172.17.0.1:9000
    aws_access_key_id: minioadmin
    aws_secret_access_key: minioadmin
    use_ssl: false
    signature_version: s3v4

storage:
  store_type: pgvector # "milvus" or "pgvector"
  milvus:
    uri: http://172.17.0.1:19530  # "https://username:password@in01-12a.aws-us-west-2.vectordb.zillizcloud.com:19538
    collection: doc_vectors
    drop_old: false
    auto_id: true
    alias: default
  pgvector:
    host: 172.17.0.1
    port: 5432
    user: postgres
    password: postgres
    database: vector_db
    collection: doc_vectors
    use_jsonb: true

search:
  search_query: "the work of a data analyst"
  search_top_k: 5

output_dir: ./output_docs
debug: false
delete_old_vectors: false
